# Generated by Django 3.2.3 on 2021-05-23 19:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RandomUUID',
            fields=[
                ('timestamp', models.UUIDField(default=uuid.uuid4, help_text='Randomly generated', primary_key=True, serialize=False)),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
