# Generated by Django 3.2.3 on 2021-05-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowryRest', '0002_randomuuid_cowrytest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomuuid',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
